services:
  - type: web
    name: studybuddy
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python studybud/manage.py migrate && python studybud/manage.py collectstatic --noinput && python studybud/manage.py runserver 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: studybud.settings
